sam-hosseini/freelancing-in-finland

README.md
Added internet subscription to the benefits section.
Could not find this in English, but the Finnish source is: [https://www.vero.fi/syventavat-vero-ohjeet/ohje-hakusivu/62486/henkil%C3%B6kuntaedut-verotuksessa/](https://www.vero.fi/syventavat-vero-ohjeet/ohje-hakusivu/62486/henkil%C3%B6kuntaedut-verotuksessa/) 4.4.1 Työnantajan järjestämä tietoliikenneyhteys
=> Add internet subscription to the benefits

README.md
KT Kirjanpito are totally happy to work in English. They specialize in this stuff and give give advice and other services also. Disclosure - my wife works there.
=> Add English accountancy

README.md
- Added a section about what to ask from a broker company when meeting them for the first time
- Changed the line with Talented to better describe how Talented operates with their community members
=> Added a section about what to ask from broker company

README.md
Applying for the startup grant extension is quite a bit simpler than the initial process, so I outlined it in a few steps.
=> Startup grant extension information added

README.md
Maybe worth adding that I'm the founder of Toughbyte and we've had over 50 contractors work through us so far for end clients such as Nokia, HSL, Yle, Edenred and others.
=> Added Toughbyte to brokers

README.md
=> Add information about residence permit required for Non-EU citizens

README.md
=> Adding Hiq to the brokers list

README.md
=> Add more examples of benefits

README.md
=> to read.me add "Notification of beneficial owners"

README.md
=> Add info about what is considered as start date of entrenepreurship

README.md
=> Add info about competing activities

README.md
=> Add Palkka.fi as an option for reporting salary

README.md
Update social insurance contributions according to 2021 values: https://www.vero.fi/yritykset-ja-yhteisot/tietoa-yritysverotuksesta/yritys_tyonantajana/sosiaalivakuutusmaksut/
=> Update 2021 social insurance contributions

README.md
This was changed in 2021: https://www.vero.fi/tulorekisteri/yritykset-ja-organisaatiot/yksityiskohtaiset-tulorekisterin-ohjeet/64028/tietojen-ilmoittaminen-tulorekisteriin-luontoisedut-ja-kustannusten-korvaukset5/#1.1.2-ty%C3%B6suhdematkalippuetu
=> Update commuting benefit

README.md
Add section about dental care plan
=> Add section about dental care plan

README.md
The invoices should not show the VAT rate or the amount of VAT.
Adding also references to the council directive and Finnish Tax
Administration instructions.
Thank you!
=> Correct VAT Reverse Charge information

README.md
For those of us who are Swedish-speaking, it might be useful to know that some of these resources are actually available in Swedish as well.
=> Fix some "only in Finnish" references

README.md
Updated IF insurance details to include recently gathered pricing information
=> Updated IF insurance details

README.md
Thank you for taking the time to create this PR 💐
I maintain this repository with limited time.
Once you send your PR, I'll review it with respect to the time you spent on creating it.
In return, I expect you to respect my time and make sure all the following conditions are met:
Thank you!
=> New broker Added.

README.md
Adding vahvistus.fi to the broker list.
=> chore: Add Vahvistus to the broker list

README.md
Thank you for taking the time to create this PR 💐
I maintain this repository with limited time.
Once you send your PR, I'll review it with respect to the time you spent on creating it.
In return, I expect you to respect my time and make sure all the following conditions are met:
Thank you!
=> Update Edenred pricing

README.md
Thank you for taking the time to create this PR 💐
I maintain this repository with limited time.
Once you send your PR, I'll review it with respect to the time you spent on creating it.
In return, I expect you to respect my time and make sure all the following conditions are met:
Thank you!
=> Update YEL income notes to 2023 README.md

README.md
I noted that the values at https://www.epassi.fi/en/employers differs from the ones displayed on this page, hence the update. This presumes that we are talking about Epassi Go, but this seems to be their suitable offering for companies with less than 20 employees (=us. 😁).
=> Update ePassi costs

README.md
Thank you for taking the time to create this PR 💐
I maintain this repository with limited time.
Once you send your PR, I'll review it with respect to the time you spent on creating it.
In return, I expect you to respect my time and make sure all the following conditions are met:
Thank you!
=> fix typo "coporate" to "corporate"

README.md
=> Add project sources
